package com.apkharden.packager.ui.barcode

import androidx.compose.foundation.Image
import androidx.compose.foundation.background
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.foundation.text.selection.SelectionContainer
import androidx.compose.foundation.verticalScroll
import androidx.compose.material.*
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.draw.clip
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.toComposeImageBitmap
import androidx.compose.ui.layout.ContentScale
import androidx.compose.ui.platform.LocalClipboardManager
import androidx.compose.ui.text.AnnotatedString
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import com.apkharden.packager.core.*
import com.apkharden.packager.ui.adb.copyImageToClipboard
import com.apkharden.packager.ui.common.pickFile
import com.apkharden.packager.ui.inspect.PageTitle
import com.apkharden.packager.ui.inspect.ValueCard
import com.apkharden.packager.ui.theme.LocalSemantic
import kotlinx.coroutines.*
import java.awt.image.BufferedImage
import java.io.File
import java.nio.file.Files
import java.nio.file.StandardCopyOption

@Composable
internal fun BarcodeScreen() {
    var decoding by remember { mutableStateOf(false) }
    var kind by remember { mutableStateOf(CodeKind.QR) }
    var typeMenu by remember { mutableStateOf(false) }
    var text by remember { mutableStateOf("") }
    var size by remember { mutableStateOf(512) }
    var generated by remember { mutableStateOf<GeneratedCode?>(null) }
    var sourceImage by remember { mutableStateOf<BufferedImage?>(null) }
    var sourceLabel by remember { mutableStateOf("") }
    var results by remember { mutableStateOf<List<DecodedCode>>(emptyList()) }
    var busy by remember { mutableStateOf(false) }
    var message by remember { mutableStateOf<String?>(null) }
    var error by remember { mutableStateOf(false) }
    val scope = rememberCoroutineScope()
    val clipboard = LocalClipboardManager.current
    val sem = LocalSemantic.current
    fun run(block: suspend () -> Unit) {
        busy = true; error = false; message = null
        scope.launch {
            try { block() }
            catch (e: CancellationException) { throw e }
            catch (e: Exception) { error = true; message = e.message ?: "操作失败，请重试" }
            finally { busy = false }
        }
    }
    fun decode(label: String, image: () -> BufferedImage) {
        results = emptyList(); sourceImage = null; sourceLabel = label
        run {
            val input = withContext(Dispatchers.IO) { image() }
            sourceImage = input
            results = withContext(Dispatchers.Default) { BarcodeTool.decode(input) }
            message = "识别到 ${results.size} 个结果"
        }
    }
    Column(Modifier.fillMaxSize().verticalScroll(rememberScrollState()).padding(28.dp), verticalArrangement = Arrangement.spacedBy(18.dp)) {
        PageTitle("二维码与条形码", "本地生成与识别，无需连接手机")
        Row(horizontalArrangement = Arrangement.spacedBy(8.dp)) {
            listOf(false to "生成码图", true to "识别图片").forEach { (value, title) ->
                OutlinedButton(enabled = !busy, onClick = { decoding = value; message = null },
                    colors = ButtonDefaults.outlinedButtonColors(backgroundColor = if (decoding == value) MaterialTheme.colors.primary.copy(alpha = .12f) else Color.Transparent)) {
                    Text(title)
                }
            }
        }
        if (!decoding) {
            Row(Modifier.fillMaxWidth(), horizontalArrangement = Arrangement.spacedBy(18.dp)) {
                Column(Modifier.weight(1f)) {
                    ValueCard {
                        Text("内容与格式", style = MaterialTheme.typography.subtitle1)
                        Spacer(Modifier.height(12.dp))
                        Box {
                            OutlinedButton(enabled = !busy, onClick = { typeMenu = true }, modifier = Modifier.fillMaxWidth()) { Text("${kind.label}  ▾") }
                            DropdownMenu(expanded = typeMenu, onDismissRequest = { typeMenu = false }) {
                                CodeKind.entries.forEach { option -> DropdownMenuItem(onClick = {
                                    kind = option; generated = null; message = null; typeMenu = false
                                }) { Text(option.label) } }
                            }
                        }
                        Text(kind.help, style = MaterialTheme.typography.caption, color = sem.subtle, modifier = Modifier.padding(vertical = 8.dp))
                        OutlinedTextField(text, { text = it; generated = null; message = null }, enabled = !busy,
                            label = { Text("要编码的内容") }, placeholder = { Text(kind.example) },
                            modifier = Modifier.fillMaxWidth().height(170.dp))
                        Row(Modifier.fillMaxWidth(), verticalAlignment = Alignment.CenterVertically) {
                            Text("${text.length} 个字符", style = MaterialTheme.typography.caption, color = sem.subtle, modifier = Modifier.weight(1f))
                            TextButton(enabled = !busy, onClick = { text = kind.example; generated = null; message = null }) { Text("填入示例") }
                        }
                        if (kind == CodeKind.QR) {
                            Row(horizontalArrangement = Arrangement.spacedBy(6.dp)) {
                                listOf(256, 512, 1024).forEach { pixels ->
                                    OutlinedButton(enabled = !busy, modifier = Modifier.weight(1f), onClick = { size = pixels; generated = null },
                                        colors = ButtonDefaults.outlinedButtonColors(backgroundColor = if (size == pixels) MaterialTheme.colors.primary.copy(alpha = .10f) else Color.Transparent)) { Text("$pixels px") }
                                }
                            }
                        }
                        Spacer(Modifier.height(10.dp))
                        Button(enabled = !busy && text.isNotEmpty(), modifier = Modifier.fillMaxWidth(), onClick = {
                            generated = null
                            run { generated = withContext(Dispatchers.Default) { BarcodeTool.generate(kind, text, size) } }
                        }) { Text(if (busy) "正在生成…" else "生成 ${kind.label}") }
                    }
                }
                Column(Modifier.weight(1f)) {
                    ValueCard {
                        Text("图片预览", style = MaterialTheme.typography.subtitle1)
                        Spacer(Modifier.height(14.dp))
                        val code = generated
                        Box(Modifier.fillMaxWidth().height(270.dp).clip(RoundedCornerShape(10.dp)).background(Color.White), contentAlignment = Alignment.Center) {
                            if (code == null) Text("生成后在这里预览", color = Color.Gray, style = MaterialTheme.typography.body2)
                            else {
                                val bitmap = remember(code) { code.image.toComposeImageBitmap() }
                                Image(bitmap, "生成的${code.kind.label}", Modifier.fillMaxSize().padding(12.dp), contentScale = ContentScale.Fit)
                            }
                        }
                        Spacer(Modifier.height(10.dp))
                        Text(code?.let { "${it.kind.label} · ${it.image.width} × ${it.image.height} px · PNG" } ?: "黑白码图，保留标准留白", color = sem.subtle, style = MaterialTheme.typography.caption)
                        if (code != null && code.kind != CodeKind.QR) SelectionContainer { Text(code.content, modifier = Modifier.padding(top = 8.dp), style = MaterialTheme.typography.body2) }
                        Spacer(Modifier.height(12.dp))
                        Row(horizontalArrangement = Arrangement.spacedBy(8.dp)) {
                            OutlinedButton(enabled = code != null && !busy, modifier = Modifier.weight(1f), onClick = { run {
                                copyImageToClipboard(code!!.png); message = "码图已复制，可直接粘贴"
                            } }) { Text("复制图片") }
                            Button(enabled = code != null && !busy, modifier = Modifier.weight(1f), onClick = {
                                val selected = pickFile("保存码图", save = true, extensions = listOf("png"), defaultName = "${kind.name.lowercase()}.png") ?: return@Button
                                val file = File(if (selected.endsWith(".png", true)) selected else "$selected.png")
                                run {
                                    withContext(Dispatchers.IO) {
                                        val temporary = Files.createTempFile(file.absoluteFile.parentFile.toPath(), ".apkharden-code-", ".png")
                                        try { Files.write(temporary, code!!.png); Files.move(temporary, file.toPath(), StandardCopyOption.REPLACE_EXISTING) }
                                        finally { Files.deleteIfExists(temporary) }
                                    }
                                    message = "已保存：${file.absolutePath}"
                                }
                            }) { Text("保存 PNG") }
                        }
                    }
                }
            }
        } else {
            ValueCard {
                Row(verticalAlignment = Alignment.CenterVertically) {
                    Column(Modifier.weight(1f)) {
                        Text("导入需要识别的图片", style = MaterialTheme.typography.subtitle1)
                        Text("支持 PNG、JPEG、BMP、GIF；可识别图片中的多个码", color = sem.subtle, style = MaterialTheme.typography.caption)
                    }
                    OutlinedButton(enabled = !busy, onClick = { decode("剪贴板图片", ::readClipboardImage) }) { Text("读取剪贴板") }
                    Spacer(Modifier.width(8.dp))
                    Button(enabled = !busy, onClick = {
                        val selected = pickFile("选择码图", extensions = listOf("png", "jpg", "jpeg", "bmp", "gif")) ?: return@Button
                        decode(File(selected).name) { BarcodeTool.readImage(File(selected)) }
                    }) { Text("选择图片") }
                }
                sourceImage?.let { input ->
                    Spacer(Modifier.height(14.dp))
                    val bitmap = remember(input) { input.toComposeImageBitmap() }
                    Image(bitmap, "待识别图片", Modifier.fillMaxWidth().height(230.dp).clip(RoundedCornerShape(10.dp)).background(Color.White).padding(12.dp), contentScale = ContentScale.Fit)
                    Text(sourceLabel, color = sem.subtle, style = MaterialTheme.typography.caption, modifier = Modifier.padding(top = 8.dp))
                }
            }
            results.forEachIndexed { index, result ->
                ValueCard {
                    Row(verticalAlignment = Alignment.CenterVertically) {
                        Text("结果 ${index + 1} · ${result.format}", modifier = Modifier.weight(1f), fontWeight = FontWeight.SemiBold)
                        TextButton(onClick = { run { clipboard.setText(AnnotatedString(result.text)); message = "识别内容已复制" } }) { Text("复制内容") }
                    }
                    OutlinedTextField(result.text, {}, readOnly = true, modifier = Modifier.fillMaxWidth().heightIn(min = 80.dp, max = 220.dp))
                }
            }
        }
        if (busy) LinearProgressIndicator(Modifier.fillMaxWidth())
        message?.let { Text(it, color = if (error) MaterialTheme.colors.error else MaterialTheme.colors.primary, style = MaterialTheme.typography.body2) }
        Text("图片与内容仅在本机处理。识别清晰度受图片尺寸、反光和遮挡影响。", color = sem.subtle, style = MaterialTheme.typography.caption)
    }
}
